### ISSUE TITLE
v0.7 add non-free dependencies

### ISSUE THREAD

**Issue by IzzySoft** [AP-Atul/music_player_lite#13]
Unfortunately, your adding of iAP added two non-free libraries. My scanner reports:

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeDep

2 offenders.
```

Strictly speaking, your app is no longer (entirely) FOSS with this. I just had to add the `NonFreeDep` and `NonFreeNet` anti-features to your listing. As those libraries won't work on Google-free devices anyway, maybe you could consider a separat FOSS build flavor (without those libs) with the next release?

For some alternative monetarization options, you can also take a look at [my snippet here](https://gitlab.com/-/snippets/1896503#monetarization).

**Comment by AP-Atul** [comment]
You know what lets get the Google dependency out.

**Comment by IzzySoft** [comment]
You mean which library brought it in? Neither-nor, I'm not an Android developer. But I see you're using gradle, so `gradle :app:dependencies` should tell you. Must be something you added in the last version, as it wasn't there before.

**Comment by AP-Atul** [comment]
Got it updated

**Comment by AP-Atul** [comment]
Starting from `v0.8` there are no more google deps (non-free dependency)

**Comment by AP-Atul** [comment]
Been busy with other work. I have big plans for the online version!

**Comment by IzzySoft** [comment]
Great to hear – looking forward to that patiently then :smiley:

**Comment by IzzySoft** [comment]
Yay! Looking forward to the next release then. Thanks a lot!
