### ISSUE TITLE
Show multiple artists when playing a track

### ISSUE THREAD

**Issue by libregeek** [AP-Atul/music_player_lite#14]
I installed and used Music Player Lite and I am very much impressed with the features available in the player. I was in search of a lightweight offline music player that doesn't require unnecessary app permissions. I have earlier used Music Player Go, but this player is much better in terms of UI and functionality.

I would really like to recommend this player to my friends and colleagues and also is planning to a review on Play Store. I liked the simplicity and less use of resources and also the user experience. I have also a couple of feature requests that may help me to use the player better.

I use the multiple tag feature in ID3v2 and have a huge collection of mp3 songs that are tagged atomically.  I would like to see the names of all artists associated with a track when the app is playing a track. Similar feature is available in Omnia (Android), Foobar2000 (Android) and Quodlibet (Linux Desktop). Here are the screenshots from the apps.

This is how I edit the MP3 on Quodlibet Metadata Editor (Ex Falso):
<img width="356" alt="Screenshot 2022-09-14 134956" src="https://user-images.githubusercontent.com/145110/190103232-1fda47f4-0830-4c0b-bad4-e199f4886cd8.png">

This is how it is displayed on Quodlibet
<img width="589" alt="Screenshot 2022-09-14 135105" src="https://user-images.githubusercontent.com/145110/190103328-cb32d4bd-6179-4e99-9c49-a6d0924181c0.png">

This is how multiple artists are displayed on Foobar2000 (when playing a track)
<img width="400" src="https://user-images.githubusercontent.com/145110/190103527-993dbc34-c296-479f-9884-845b8b5699cc.jpg">

This is how multiple artists are displayed on tracklist on Omnia
<img width="400" src="https://user-images.githubusercontent.com/145110/190103711-b38c3e03-d9f5-402b-b19c-5a8e947cbf84.jpg">

This is how multiple are displayed when playing a track on Omnia
<img width="400" src="https://user-images.githubusercontent.com/145110/190103818-7c0ae078-0b68-49b9-b6f0-681ba8815429.jpg">

**Comment by AP-Atul** [comment]
Are you suggesting feature to add Tag editor?

**Comment by libregeek** [comment]
> Are you suggesting feature to add Tag editor?

No. tag editor feature is not required. It's just to display multiple artists in a track.

**Comment by AP-Atul** [comment]
The player does show the artists name. I will test it out with music which has multiple artists.
The only way currently I get the artist is by reading from Media Store. There might be some limitations there.

Will recheck

**Comment by libregeek** [comment]
The app shows multiple artists if they are added to a single tag separated by comma or semi-colon. But if the multiple artists are added as separate `artist` tags then it would show only the first artist tag. I believe the latter is the standard approach as per ID3v2.

I saw the limitations with MediaStore API. But there are other apps (Omnia, Foobar2000) that supports multiple artists. 

I can also help with little bit coding (I am newbie in Android development) and testing the features.

**Comment by AP-Atul** [comment]
Would love any sort of contribution, you are welcome to fork -> update -> make a PR!

**Comment by AP-Atul** [comment]
want to stick to the media store for content. if the media store has multiple artists, this will work anyway.
