### ISSUE TITLE
add a track repeat function to the notifications

### ISSUE THREAD

**Issue by Wjxfi** [AP-Atul/music_player_lite#15]
Like here
![Polish_20221022_125219779.jpg](https://user-images.githubusercontent.com/113500363/197333101-8378c8ab-cf3e-47cb-acfa-21770b0c075b.jpg)
this place appears if you open the notification
![Polish_20221022_130006629.jpg](https://user-images.githubusercontent.com/113500363/197333394-1ef454f0-32cf-4c5e-bd51-a360eeee9e91.jpg)
![Polish_20221022_130050253.jpg](https://user-images.githubusercontent.com/113500363/197333398-b110822a-b5b3-45dd-a663-9a7a9a75f7d7.jpg)

**Comment by AP-Atul** [comment]
There is limit on no of actions in notification bar
