### ISSUE TITLE
When these buttons are pressed twice, they rewind for 10 seconds.

### ISSUE THREAD

**Issue by Wjxfi** [AP-Atul/music_player_lite#16]
![IMG_20221022_130918.jpg](https://user-images.githubusercontent.com/113500363/197333723-7b8c737c-0565-4f90-9cca-91bdfb4b6bde.jpg)
### Please add

**Comment by AP-Atul** [comment]
These buttons are meant to rewind the songs. I don't want to add extra two buttons so closing this
