### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by VishnuSanal** [AP-Atul/music_player_lite#22]
Hi, @AP-Atul!

I imported the project into Android Studio. But, Android Studio wasn't recognizing the Gradle build files. I wasn't able to open the "Android" view from Project Structure menu nor to build/run the project.

I digged around for a while. I tried moving every file inside of `src/` to the root directory and the project started getting recognized by Android Studio. This is weird -- aren't you using Android Studio for development?

Also, I had to modify `debug` on `app/build.gradle:7` to `release` to run the project.

Was wondering it this normal?! Or are you using some other build systems & is there any easier ways to import the project into Android Studio than manually copying the files!?

**Comment by AP-Atul** [comment]
I'm using Android studio. It may be that the build files could be of older versions. I never had any issues with it on any of my systems (Mac, Linux)
