### ISSUE TITLE
fix this

### ISSUE THREAD

**Issue by Wjxfi** [AP-Atul/music_player_lite#24]
![297400.jpg](https://user-images.githubusercontent.com/113500363/210222568-77de7f86-6150-4dbf-8d1f-3661cbebd228.jpg)
in version 0.12

**Comment by AP-Atul** [comment]
Fixed in [v0.13](https://github.com/AP-Atul/music_player_lite/releases/tag/v0.13)

**Comment by AP-Atul** [comment]
Can you send me that file?

**Comment by AP-Atul** [comment]
god damn, you are right :sweat_smile:

**Comment by AP-Atul** [comment]
The problem was that I did not push that fix earlier and missed in the release.
After this gets fixed, if for some reason the app is not able to determine the bitrate for the file, it will display the result
