### ISSUE TITLE
dedicated package name for the online variant

### ISSUE THREAD

**Issue by IzzySoft** [AP-Atul/music_player_lite#3]
You currently provide 2 versions of your music player: one without online functionalities (for the paranoid like me :speak_no_evil:), and one with online functionality (for everybody else) – which is a great idea! Unfortunately, both have the very same `packageName`. May I suggest to give the online variant its own unique `packageName`, e.g. `com.atul.musicplayeronline`?

**Background:** the combination of `packageName` and `versionCode` is a unique identifier. I've just added the offline variant to my repo (will [become available here](https://apt.izzysoft.de/fdroid/index/apk/com.atul.musicplayerlite) in about 2 hours from now). I'd like to add the online variant as well, but I can't – due to above mentioned restrictions: two apps cannot share the same `packageName`.

There's one more minor issue: your tag says `v0.1` – but `versionName` is not `0.1`, it's simply identical to `versionCode`. So you might wish to adjust either `versionName` or tag name with future releases :wink:

Thanks, and all the best for your project! I hope you like the idea of your app being made easier discoverable through my repo (and also easier to keep updated on the user's devices). If so, be welcome using [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from your Readme. If you wish, your app could also be brought to [F-Droid.org](https://f-droid.org/)s own repo, which has more prestige (and higher trust) than mine.

**Comment by AP-Atul** [comment]
The thought of changing the package name crossed my mind too everytime during testing.
I will change the package name and the version code too. And yes it can be on your repo

**Comment by IzzySoft** [comment]
Great, thanks! Please drop me a note here when the changed version is available and I'll pick it up then.

**Comment by AP-Atul** [comment]
I have updated the version codes and made a new release, let me know any more changes or anything you would like to see in upcoming updates.  😊

**Comment by IzzySoft** [comment]
Looks perfect, thanks! And you've even integrated the badge for both, wonderful!! The new one should lead to the expected details in about 3.5h from now with the next sync. I've also pulled the update for the offline version manually (as my updater would fail, thinking "I have `1`, which is higher than `0.2`"). Future updates should work fine, and be pulled within 24h of your attaching them to new tags.

**Comment by IzzySoft** [comment]
PS: If you wish, I can make a PR sending you the metadata in [Fastlane structure](https://gitlab.com/snippets/1895688). That way you could control description, screenshots etc. and changes would be pulled along with the updates. Just let me know if you're interested.

**Comment by AP-Atul** [comment]
Yeah sure! Something new to learn

**Comment by IzzySoft** [comment]
OK, give me a few minutes then. Fastlane originally is a "one-for-all", but you essentially have 2 apps in 1 repo (different flavors, which devs usually use [Triple-T](https://gitlab.com/snippets/1901490) for). I find Triple-T structures a bit confusing. Fastlane now also can be used for multiple flavors; you'd need to tell then how you want to deal with that (or move the pieces as you wish and let me know). My updater can deal with any location for Fastlane, so you're basically free to choose. F-Droid itself currently does not.

Going by your `build.gradle` I have no idea how you separate the flavors, so I leave splitting to you. My PR will hence use the default location for Fastlane, and target the offline variant. We can go on from there later.

**Comment by AP-Atul** [comment]
😅 I never planned the two versions, just created separate branches and developed each the way along. I never edit the build files, learnt Android development on my own so that's that.
I will try my best to keep it organized.

**Comment by IzzySoft** [comment]
Ah, well… My updater cannot deal with branches (because Github API misses some pieces for that). So we leave it with one fastlane tree fro now, differences are minimal anyway. Images are even symlinked on my end: so what I pull for lite, also appears for online. Just the `full_description.txt` has an additional line for the online variant (for the online feature). If you want the same description for both (and point out the difference "inline"), that would work fine as well.

**Comment by IzzySoft** [comment]
PS: For formatting of `full_description.txt`, find some hints [in my wiki](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). If you only plan for my repo, Markdown or HTML both work fine. If you plan for F-Droid or Play, I'd recommend what that wiki page calls "Markdown lite", as that should work for all 3 (not sure how Play deals with links, though).

Enjoy! And feel free to ask if you think you're stuck with Fastlane details. As long as it's about the structures, I guess I can help; I just never used their binaries, so I cannot help with that part (which will probably not be needed anyway).

Thanks for merging that fast! I've enabled pulling Fastlane for the "lite" variant for now. Let me know when we shall adjust something for the "online" variant, concerning summary/description.

**Comment by AP-Atul** [comment]
I will let you know about it

**Comment by AP-Atul** [comment]
I was thinking of having this app on f-droid as well

**Comment by IzzySoft** [comment]
No prob if the inclusion criteria are met :smiley: My above link concerning formatting covers that. When you think you're ready, just go ahead and open a [Request For Packaging](https://gitlab.com/fdroid/rfp/-/issues).

**Comment by IzzySoft** [comment]
Congrats to the F-Droid listing, @AP-Atul! I see the Readme now carries both badges – so I take it you want me to keep your app in my repo? As it's a reproducible build at F-Droid, I don't see an issue with that and will mark it "keep" if you confirm – or remove it it you prefer that :wink:

**Comment by AP-Atul** [comment]
Just keep it

**Comment by IzzySoft** [comment]
Marked for keep then. Thanks!

**Comment by IzzySoft** [comment]
Just wondering: There was no APK for the "online" variant anymore since v0.3 – is it discontinued? Shall I remove it from my repo?

**Comment by AP-Atul** [comment]
I think it's better to call it discontinued. Good to remove

**Comment by IzzySoft** [comment]
OK, then I'll remove it, thanks!
