### ISSUE TITLE
Files stored in the raw/assets folder

### ISSUE THREAD

**Issue by abdulbasid123** [AP-Atul/music_player_lite#37]
How can I retrieve the audio files saved/stored in the raw/assets folder of the app (even it means to exclude Artist and Album out) ?

I want to build an app that will play only the audio files stored in the raw folder, but in a playlist and customize uis like (Music Player Lite).

I have downloaded the Music Player Lite code and able to edit and even customize the uis better, I don't know how to make it retrieve the raw files.

Any one could help me ? Or direct me to a link ?

**Comment by AP-Atul** [comment]
This should work I guess
```
MediaPlayer mPlayer = MediaPlayer.create(context, R.raw.soundclip);
mPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
mPlayer.start();
```
