### ISSUE TITLE
add support for opus

### ISSUE THREAD

**Issue by Uranite** [AP-Atul/music_player_lite#5]

**Comment by AP-Atul** [comment]
I am using Android default Media Player api which supports opus (.ogg). I will test that with some files to support the issue.

Thanks

**Comment by Uranite** [comment]
yeah, the opus file i have is .opus, i think thats the issue

**Comment by AP-Atul** [comment]
I thought I wrote any replied 😅. But its still here. So i tested with some .opus files and they work and show like all files. May be the one you are trying is not register by media store itself
Try one thing move that file to some other folder and reopen the app and find it. May be it would appear
