### ISSUE TITLE
Song Download 

### ISSUE THREAD

**Issue by brnwlshubh** [AP-Atul/music_player_lite#7]
@AP-Atul 
Song is not downloading from Online version of app.

**Comment by AP-Atul** [comment]
Which song have you tried with? or All songs won't download

**Comment by brnwlshubh** [comment]
I tried some songs but not downloaded any of them.
Have a try from your side too.

**Comment by AP-Atul** [comment]
Sure. Will take a look.

**Comment by brnwlshubh** [comment]
Ok, I see.So when next version will going to release?

**Comment by AP-Atul** [comment]
Soon
