### ISSUE TITLE
how to import music in app?

### ISSUE THREAD

**Issue by danyow-cheung** [AP-Atul/music_player_lite#8]
i pull .mp3 file to android emulator , and the android files do shown these files,but when i am to refresh music list,it just does't work, the player can't not response correctly

**Comment by danyow-cheung** [comment]
i had tried to restart still not working

**Comment by AP-Atul** [comment]
I haven't tested much on emulator but I was able to see files from Downloads folder.
Might need to look more into.

Are you able to see files from a non emulator device?
