### ISSUE TITLE
EDITOR doesn't update what you input

### ISSUE THREAD

**Issue by Vierusha** [AP-Atul/music_player_lite#9]
EDITOR (music tag).....it doesn't change what you input...it it will toast that it is "updated" but it still the same when you exit the Editor layout

**Comment by AP-Atul** [comment]
I have also seen few issues with it not working. I need to some more checks to respond with if the change didn't work.
Thanks for trying out the app🙂

**Comment by AP-Atul** [comment]
not going to add a Tag Editor anytime soon!
